[pytest]
pythonpath = src
testpaths = tests
filterwarnings =
    ignore:ast.NameConstant is deprecated.*:DeprecationWarning:reportlab.lib.rl_safe_eval
    ignore:.*doesn't match a supported version.*:Warning